//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.CompanyReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyReference.IMyCompanyPublicService")]
    public interface IMyCompanyPublicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompanyPublicService/GetPublicInformation", ReplyAction="http://tempuri.org/IMyCompanyPublicService/GetPublicInformationResponse")]
        string GetPublicInformation();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyCompanyPublicServiceChannel : WebApplication2.CompanyReference.IMyCompanyPublicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyCompanyPublicServiceClient : System.ServiceModel.ClientBase<WebApplication2.CompanyReference.IMyCompanyPublicService>, WebApplication2.CompanyReference.IMyCompanyPublicService {
        
        public MyCompanyPublicServiceClient() {
        }
        
        public MyCompanyPublicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyCompanyPublicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyCompanyPublicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyCompanyPublicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPublicInformation() {
            return base.Channel.GetPublicInformation();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyReference.IMyCompanyConfidentialService")]
    public interface IMyCompanyConfidentialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompanyConfidentialService/GetCofidentialInformation", ReplyAction="http://tempuri.org/IMyCompanyConfidentialService/GetCofidentialInformationRespons" +
            "e")]
        string GetCofidentialInformation();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyCompanyConfidentialServiceChannel : WebApplication2.CompanyReference.IMyCompanyConfidentialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyCompanyConfidentialServiceClient : System.ServiceModel.ClientBase<WebApplication2.CompanyReference.IMyCompanyConfidentialService>, WebApplication2.CompanyReference.IMyCompanyConfidentialService {
        
        public MyCompanyConfidentialServiceClient() {
        }
        
        public MyCompanyConfidentialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyCompanyConfidentialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyCompanyConfidentialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyCompanyConfidentialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCofidentialInformation() {
            return base.Channel.GetCofidentialInformation();
        }
    }
}
